/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_thu_xface_libs_DemoLibrary */

#ifndef _Included_edu_thu_xface_libs_DemoLibrary
#define _Included_edu_thu_xface_libs_DemoLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_thu_xface_libs_DemoLibrary
 * Method:    demotest
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_edu_thu_xface_libs_DemoLibrary_demotest
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
