/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_thu_xface_libs_XFaceLibrary */

#ifndef _Included_edu_thu_xface_libs_XFaceLibrary
#define _Included_edu_thu_xface_libs_XFaceLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_thu_xface_libs_XFaceLibrary
 * Method:    nativeInitFacerec
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_thu_xface_libs_XFaceLibrary_nativeInitFacerec
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_thu_xface_libs_XFaceLibrary
 * Method:    nativeFacerec
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_edu_thu_xface_libs_XFaceLibrary_nativeFacerec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     edu_thu_xface_libs_XFaceLibrary
 * Method:    nativeDestoryFacerec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_thu_xface_libs_XFaceLibrary_nativeDestoryFacerec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_thu_xface_libs_XFaceLibrary
 * Method:    testLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_thu_xface_libs_XFaceLibrary_testLong
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
