#ifndef CONSTANT_H
#define CONSTANT_H 

//Constant.h
//
//This file defines common constant parameters for radio level simulation. 
//
//Programmed by Ryota Kimura
//
//History: 
//2010.10.21 Ryota Kimura
//Programming start
//



// 2012.05.27
#define TEST_MESSAGE                                        FLAG_OFF // when "1", the simlation shows many comments on the display
#define TEST_MESSAGE_LOOP_FOR_MONTE_CARLO_TRIAL             FLAG_OFF
#define TEST_MESSAGE_LOOP_FOR_SUBFRAME                      FLAG_OFF
#define TEST_MESSAGE_REFRESH                                FLAG_OFF
#define TEST_MESSAGE_CELL_SELECTION                         FLAG_OFF
#define TEST_MESSAGE_PATH_LOSS_CALC                         FLAG_OFF
#define TEST_MESSAGE_SCHEDULER                              FLAG_OFF
#define TEST_MESSAGE_SINR_CALC                              FLAG_OFF
#define TEST_MESSAGE_TPC                                    FLAG_OFF
#define TEST_MESSAGE_NODE_MEMORY                            FLAG_OFF
#define TEST_MESSAGE_BLOCK_ERROR                            FLAG_OFF
#define TEST_MESSAGE_LINK_ADAPTATION                        FLAG_OFF
#define TEST_MESSAGE_TBS_DETERMINATION                      FLAG_OFF
#define TEST_MESSAGE_CSI_MEASUREMENT                        FLAG_OFF


//2013.08.30
// Consider the spatial correlation characterisics for the large-scale parameters in ITU-R M.2135 channel models. 
#define FLAG_CONSIDER_SPATIAL_CORRELATION_FOR_ITUR_M2135_LSP FLAG_OFF


//// 2012.06.11
// Available only for calibration of downlink against TR36.814 
#define FLAG_NON_DIAGONAL_ELEMENT_IS_INTERFERENCE_IN_SINR   FLAG_OFF

// 2012.10.19
// Used in the scheduler function with a power-headroom-like consideration and with UE prioritization. 
#define FLAG_ALWAYS_ASSIGN_ALL_RB_TO_UE_PER_SECTOR          FLAG_OFF

// 2012.10.15 added 
// These values define how to calculate SINR. 
#define MOD_TYPE_NONE -1 
#define MOD_TYPE_MULTICARRIER 0
#define MOD_TYPE_SINGLECARRIER 1

// 2012.05.10
#define CHECK_ERROR 1
#define CHECK_CORRECT 0

#define PI 3.14159265358979323
#define LIGHT_SPEED 299792458.0 // unit = meter/sec
#define DBL_MAX_BY_10 (DBL_MAX / 10.0) // Tentative

// Added 2012.06.09
// Currently NOT used
#define FLAG_INTERFERENCE_SPATIAL_CHARACTERISTICS 0

// 2012.01.30 
// CDF record for SINR
#define CDF_SINR_MAX_DB 50.0
#define CDF_SINR_MIN_DB -50.0 
#define CDF_SINR_STEP_DB 0.1 // this value must be positive. 
// CDF record for TX power
#define CDF_TX_POWER_MAX_DBM 50.0
#define CDF_TX_POWER_MIN_DBM -50.0
#define CDF_TX_POWER_STEP_DBM 0.1 // this value must be positive. 
// CDF record for RX power 
#define CDF_RX_POWER_MAX_DBM 0.0
#define CDF_RX_POWER_MIN_DBM -200.0
#define CDF_RX_POWER_STEP_DBM 0.1 // this value must be positive. 
// CDF record for spectral efficiency per link
#define CDF_SPECTRAL_EFFICIENCY_PER_LINK_MIN_BPSPHZ 0.0
#define CDF_SPECTRAL_EFFICIENCY_PER_LINK_MAX_BPSPHZ 20.0
#define CDF_SPECTRAL_EFFICIENCY_PER_LINK_STEP_BPSPHZ 0.01
// CDF record for sum spectral efficiency
#define CDF_SUM_SPECTRAL_EFFICIENCY_MIN_BPSPHZ 0.0
#define CDF_SUM_SPECTRAL_EFFICIENCY_MAX_BPSPHZ 1000.0
#define CDF_SUM_SPECTRAL_EFFICIENCY_STEP_BPSPHZ 0.1
// The number of loops to display temporal CDF results
#define NUM_SUBFRAME_DISPLAY_TEMPORAL_CDF_RESULT 100
#define NUM_SUBFRAME_FOR_DISPLAY 1
#define TEMPORAL_CDF_005 0.05 
#define TEMPORAL_CDF_050 0.50
#define CDF_PRIMARY 0
#define CDF_SECONDARY 1
#define CDF_SINR 0
#define CDF_SPECTRAL_EFFICIENCY 1
#define CDF_TX_POWER 2
#define CDF_SUM_SPECTRAL_EFFICIENCY_DL 3
#define CDF_SUM_SPECTRAL_EFFICIENCY_UL 4
#define CDF_SUM_SYSTEM_SPECTRAL_EFFICIENCY_DL 5 // "Sum system spectral efficiency" means sum spectral efficiency per primary OR secondary system cell. 
#define CDF_SUM_SYSTEM_SPECTRAL_EFFICIENCY_UL 6 // "Sum system spectral efficiency" means sum spectral efficiency per primary OR secondary system cell. 
#define CDF_SINR_DL 7
#define CDF_SINR_UL 8
#define CDF_SPECTRAL_EFFICIENCY_DL 9
#define CDF_SPECTRAL_EFFICIENCY_UL 10
#define CDF_TX_POWER_DL 11
#define CDF_TX_POWER_UL 12

// 2012.02.06
// For duplex mode 
#define DUPLEX_MODE_FDD 0
#define DUPLEX_MODE_TDD 1
#define DUPLEX_MODE_FULL_DUPLEX 10

// 2012.02.06
// For pair channel (in FDD)
#define FDD_CHANNEL_PAIR_HIGH 1 // The higher channel is used for downlink usually in FDD. 
#define FDD_CHANNEL_PAIR_LOW 0 // The lower channel is used for uplink usually in FDD.  

// For frame configuration
#define MAX_NUM_SUBFRAME_PER_RADIO_FRAME 10 //  
#define MAX_NUM_SLOT_PER_SUBFRAME 1 // 2

// 2012.02.03
// For the combination of the time-domain sharing and co-channel use
#define COMBINATION_TIME_DOMAIN_SHARING_AND_COCHANNEL_USE_ON 1
#define COMBINATION_TIME_DOMAIN_SHARING_AND_COCHANNEL_USE_OFF 0
#define COMBINATION_FIRST_TPC 0
#define COMBINATION_SECOND_TPC 1

// 2012.03.06
#define MAX_NUM_ANTENNA 64

// Simulation mode
#define SIM_MODE_TIME_DEPENDENT 1
#define SIM_MODE_TIME_INDEPENDENT 0

// Communication Direction
#define COMM_DIRECTION_DOWNLINK 1
#define COMM_DIRECTION_UPLINK 0

// 2012.08.01
#define MAX_NUM_TRIAL_FOR_SECONDARY_BS_PLACEMENT 50
#define MAX_NUM_SECONDARY_BS_PER_PRIMARY_BS 600
// 2013.03.07 
#define MAX_NUM_PRIMARY_BS 19 // Based on TR36.814
#define MAX_NUM_SECONDARY_BS (MAX_NUM_PRIMARY_BS * MAX_NUM_SECONDARY_BS_PER_PRIMARY_BS)
#define MAX_NUM_BS (MAX_NUM_PRIMARY_BS + MAX_NUM_SECONDARY_BS)
#define MAX_NUM_RB MAX_NUM_RB_TBS
#define MAX_NUM_SUBBAND 1

// 2013.11.20 
#define MAX_NUM_COMPONENT_CARRIER_PER_SECTOR 1 /**< Max number of component carriers per sector */

// 2012.11.07
#define MAX_NUM_RB_TBS 110 // TS36.213
#define MAX_NUM_MCS_TBS 27 // TS36.213
#define MAX_NUM_MCS 32 // TS36.213
// 2013.06.11 
#define NUM_BLER_TABLE 1 // UL and DL
#define MAX_NUM_CQI 16 // TS36.213
#define MAX_NUM_SINR_IDX 50 // Based on a BLER table which is generated by LLS

// 2013.02.06 
#define SUBFRAME_TYPE_NORMAL 0 
#define SUBFRAME_TYPE_SYNC_EVEN 1 
#define SUBFRAME_TYPE_SYNC_AND_BROADCAST_EVEN 2
#define SUBFRAME_TYPE_SYNC_ODD 3 
#define SUBFRAME_TYPE_SYNC_AND_BROADCAST_ODD 4
#define NUM_RB_6RB 6 
#define NUM_RB_15RB 15
#define NUM_RB_25RB 25 
#define NUM_RB_50RB 50 
#define NUM_RB_75RB 75 
#define NUM_RB_100RB 100

// 2013.02.06
#define NUM_SYMBOL_PER_SUBFRAME_NORMAL_CP 14
#define NUM_SYMBOL_PER_SUBFRAME_EXTENDED_CP 12

// 2013.02.06 
#define NUM_ANTENNA_PORT_1 1
#define NUM_ANTENNA_PORT_2 2
#define NUM_ANTENNA_PORT_4 4
#define NUM_PDCCH_SYMBOL_PER_SF_1 1
#define NUM_PDCCH_SYMBOL_PER_SF_2 2
#define NUM_PDCCH_SYMBOL_PER_SF_3 3
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_NUM_ANTENNA_PORT_1 8
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_NUM_ANTENNA_PORT_2 16
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_NUM_ANTENNA_PORT_4 24
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PDCCH_1_NUM_ANTENNA_PORT_1 2
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PDCCH_1_NUM_ANTENNA_PORT_2 4
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PDCCH_1_NUM_ANTENNA_PORT_4 4
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PDCCH_2_NUM_ANTENNA_PORT_1 2
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PDCCH_2_NUM_ANTENNA_PORT_2 4
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PDCCH_2_NUM_ANTENNA_PORT_4 8
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PDCCH_3_NUM_ANTENNA_PORT_1 2
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PDCCH_3_NUM_ANTENNA_PORT_2 4
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PDCCH_3_NUM_ANTENNA_PORT_4 8
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PBCH_EVEN_NUM_ANTENNA_PORT_1 2
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PBCH_EVEN_NUM_ANTENNA_PORT_2 4
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PBCH_EVEN_NUM_ANTENNA_PORT_4 8
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PBCH_ODD_NUM_ANTENNA_PORT_1 1
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PBCH_ODD_NUM_ANTENNA_PORT_2 2
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PBCH_ODD_NUM_ANTENNA_PORT_4 4
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_PER_PBCH_NONE 0
#define NUM_CELL_SPECIFIC_REFERENCE_SIGNAL_PER_RB_PER_SF_NONE 0
#define NUM_PBCH_RE_PER_RB_PER_SF_EVEN 48
#define NUM_PBCH_RE_PER_RB_PER_SF_ODD 24
#define NUM_PBCH_RE_PER_RB_PER_SF_NONE 0
#define NUM_SYNC_SIGNAL_RE_PER_RB_PER_SF_EVEN 12
#define NUM_SYNC_SIGNAL_RE_PER_RB_PER_SF_ODD 6
#define NUM_SYNC_SIGNAL_RE_PER_RB_PER_SF_NONE 0

// Distance dependent loss mode
#define DIST_LOSS_FREE_SPACE 0
#define DIST_LOSS_DOCOMO_MICROCELL 1
#define DIST_LOSS_80211n 2
#define DIST_LOSS_ITUR_M1225_PED 3
#define DIST_LOSS_3GPP_TR25814_MACROCELL 4
#define DIST_LOSS_3GPP_TR25814_MICROCELL_OUT_TO_IN 5
#define DIST_LOSS_3GPP_TR25814_MICROCELL_OUT_TO_OUT 6
#define DIST_LOSS_3GPP_TR36814_OUT_MACROCELL 7
#define DIST_LOSS_3GPP_TR36814_OUT_PICOCELL 8

#define DIST_LOSS_ITUR_M2135_INDOORHOTSPOT 100
#define DIST_LOSS_ITUR_M2135_URBANMICRO 101
#define DIST_LOSS_ITUR_M2135_URBANMACRO 102
#define DIST_LOSS_ITUR_M2135_SUBURBANMACRO 103
#define DIST_LOSS_ITUR_M2135_RURALMACRO 104

#define DIST_LOSS_3GPP_TR36828_ISOLATED_PICO_CELL 200
#define DIST_LOSS_3GPP_TR36828_MULTI_PICO_SCENARIO_PICO_TO_PICO 201
#define DIST_LOSS_3GPP_TR36828_MULTI_PICO_SCENARIO_PICO_TO_UE 202
#define DIST_LOSS_3GPP_TR36828_MULTI_PICO_SCENARIO_UE_TO_UE 203
#define DIST_LOSS_3GPP_TR36828_MULTI_MACRO_PICO_SCENARIO_MACRO_TO_MACRO 204
#define DIST_LOSS_3GPP_TR36828_MULTI_MACRO_PICO_SCENARIO_MACRO_TO_OUTDOOR_PICO 205
#define DIST_LOSS_3GPP_TR36828_MULTI_MACRO_PICO_SCENARIO_MACRO_TO_UE 206
#define DIST_LOSS_3GPP_TR36828_MULTI_MACRO_PICO_SCENARIO_OUTDOOR_PICO_TO_OUTDOOR_PICO 207
#define DIST_LOSS_3GPP_TR36828_MULTI_MACRO_PICO_SCENARIO_OUTDOOR_PICO_TO_UE 208
#define DIST_LOSS_3GPP_TR36828_MULTI_MACRO_PICO_SCENARIO_UE_TO_UE 209

#define DIST_LOSS_3GPP_TR36873_URBANMICRO_3D 301
#define DIST_LOSS_3GPP_TR36873_URBANMACRO_3D 302


// Flag for Line-of-sight probability for distance-dependent loss
#define FLAG_DIST_LOSS_NOT_DEFINE -1 
#define FLAG_DIST_LOSS_LOS 1 
#define FLAG_DIST_LOSS_NLOS 0
#define FLAG_DIST_LOSS_INDOOR 1
#define FLAG_DIST_LOSS_OUTDOOR 0
#define DISTANCE_LOS_ITUR_M2135_INDOORHOTSPOT 18.0
#define DISTANCE_NLOS_ITUR_M2135_INDOORHOTSPOT 37.0
#define DISTANCE_LOS_ITUR_M2135_SUBURBANMACRO 10.0
#define DISTANCE_LOS_ITUR_M2135_RURALMACRO 10.0

// Parameter ranges for distance-dependent loss models
// Indoor hotspot scenario
#define DIST_LOSS_ITUR_M2135_INDOORHOTSPOT_LOS_DISTANCE_MIN 3.0
#define DIST_LOSS_ITUR_M2135_INDOORHOTSPOT_LOS_DISTANCE_MAX 100.0
#define DIST_LOSS_ITUR_M2135_INDOORHOTSPOT_HIGH_ANT_MIN 3.0
#define DIST_LOSS_ITUR_M2135_INDOORHOTSPOT_HIGH_ANT_MAX 6.0
#define DIST_LOSS_ITUR_M2135_INDOORHOTSPOT_LOW_ANT_MIN 1.0
#define DIST_LOSS_ITUR_M2135_INDOORHOTSPOT_LOW_ANT_MAX 2.5
#define DIST_LOSS_ITUR_M2135_INDOORHOTSPOT_NLOS_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_INDOORHOTSPOT_NLOS_DISTANCE_MAX 150.0

// Urban micro scenario
#define DIST_LOSS_ITUR_M2135_URBANMICRO_LOS_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_URBANMICRO_LOS_DISTANCE_MAX 5000.0
#define DIST_LOSS_ITUR_M2135_URBANMICRO_NLOS_LOW_ANT_MIN 1
#define DIST_LOSS_ITUR_M2135_URBANMICRO_NLOS_LOW_ANT_MAX 2.5
#define DIST_LOSS_ITUR_M2135_URBANMICRO_NLOS_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_URBANMICRO_NLOS_DISTANCE_MAX 2000.0
#define DIST_LOSS_ITUR_M2135_URBANMICRO_OTOI_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_URBANMICRO_OTOI_DISTANCE_MAX 1000.0
#define DIST_LOSS_ITUR_M2135_URBANMICRO_OTOI_DISTANCE_TO_WALL_MAX 25.0

// Urban macro scenario
#define DIST_LOSS_ITUR_M2135_URBANMACRO_LOS_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_URBANMACRO_LOS_DISTANCE_MAX 5000.0
#define DIST_LOSS_ITUR_M2135_URBANMACRO_NLOS_HIGH_ANT_MIN 10.0
#define DIST_LOSS_ITUR_M2135_URBANMACRO_NLOS_HIGH_ANT_MAX 150.0
#define DIST_LOSS_ITUR_M2135_URBANMACRO_NLOS_LOW_ANT_MIN 1.0
#define DIST_LOSS_ITUR_M2135_URBANMACRO_NLOS_LOW_ANT_MAX 10.0
#define DIST_LOSS_ITUR_M2135_URBANMACRO_NLOS_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_URBANMACRO_NLOS_DISTANCE_MAX 5000.0

// Suburban macro scenario
#define DIST_LOSS_ITUR_M2135_SUBURBANMACRO_LOS_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_SUBURBANMACRO_LOS_DISTANCE_MAX 5000.0
#define DIST_LOSS_ITUR_M2135_SUBURBANMACRO_HIGH_ANT_MIN 10.0
#define DIST_LOSS_ITUR_M2135_SUBURBANMACRO_HIGH_ANT_MAX 150.0
#define DIST_LOSS_ITUR_M2135_SUBURBANMACRO_LOW_ANT_MIN 1.0
#define DIST_LOSS_ITUR_M2135_SUBURBANMACRO_LOW_ANT_MAX 10.0
#define DIST_LOSS_ITUR_M2135_SUBURBANMACRO_NLOS_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_SUBURBANMACRO_NLOS_DISTANCE_MAX 5000.0

// Rural macro scenario
#define DIST_LOSS_ITUR_M2135_RURALMACRO_LOS_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_RURALMACRO_LOS_DISTANCE_MAX 10000.0
#define DIST_LOSS_ITUR_M2135_RURALMACRO_HIGH_ANT_MIN 10.0
#define DIST_LOSS_ITUR_M2135_RURALMACRO_HIGH_ANT_MAX 150.0
#define DIST_LOSS_ITUR_M2135_RURALMACRO_LOW_ANT_MIN 1.0
#define DIST_LOSS_ITUR_M2135_RURALMACRO_LOW_ANT_MAX 10.0
#define DIST_LOSS_ITUR_M2135_RURALMACRO_NLOS_DISTANCE_MIN 10.0
#define DIST_LOSS_ITUR_M2135_RURALMACRO_NLOS_DISTANCE_MAX 5000.0

// Urban micro 3D scenario
#define DIST_LOSS_ITUR_M2135_URBANMICRO_3D_OTOI_DISTANCE_TO_WALL_MAX 25.0

// Urban macro 3D scenario
#define DIST_LOSS_ITUR_M2135_URBANMACRO_3D_OTOI_DISTANCE_TO_WALL_MAX 25.0


// Sector type
#define MAX_NUM_SECTOR 3
#define MAX_NUM_SECTOR_PRIMARY_BS MAX_NUM_SECTOR
#define MAX_NUM_SECTOR_SECONDARY_BS MAX_NUM_SECTOR
#define MAX_NUM_SECTOR_PRIMARY_UE 1
#define MAX_NUM_SECTOR_SECONDARY_UE 1
#define MAX_NUM_SECTOR_MASTER_UE 1
#define MAX_NUM_SECTOR_FIXED_RELAY 1
#define MAX_NUM_SECTOR_MOBILE_RELAY 1
#define NUM_SECTOR_OMNI 1
#define NUM_SECTOR_THREE 3
#define NUM_SECTOR_SIX 6
#define SECTOR_ANGLE_WIDTH_THREE_RADIAN (PI * 2.0 / 3.0)
#define SECTOR_ANGLE_OFFSET_THREE_RADIAN (PI / 6.0)
#define SECTOR_ANGLE_WIDTH_SIX_RADIAN (PI * 1.0 / 3.0)
#define SECTOR_ANGLE_OFFSET_SIX_RADIAN (PI / 6.0)

// Node type
#define NODE_TYPE_PRIMARY_BS 0
#define NODE_TYPE_PRIMARY_UE 1
#define NODE_TYPE_SECONDARY_BS 2
#define NODE_TYPE_SECONDARY_UE 3
#define NODE_TYPE_BS 10
#define NODE_TYPE_UE 20

// Node mobility type
#define NODE_MOBILITY_FIXED 0
#define NODE_MOBILITY_MOBILE 1

// Node angle (used for secondary system)
#define NODE_ANGLE_UNIFORM 1
#define NODE_ANGLE_RANDOM 0

// 2012.01.28
// The max number of secondary system circles per primary site
#define MAX_NUM_SECONDARY_BS_CIRCLE_PER_PRIMARY_SITE 5

// Scheduling mode
#define SCHEDULE_UE_PRIORITY_WITH_CRE 1 // 2012.10.31
#define SCHEDULE_UE_PRIORITY_WITHOUT_CRE -1 // 2012.10.31
#define SCHEDULE_UE_PRIORITY_NONE 0 // 2012.10.31

// FFT or IFFT
#define FFT_FLAG 0
#define IFFT_FLAG 1

// Secondary system mode
#define S_MODE_NONE 0
#define S_MODE_GRAY 1
#define S_MODE_GREEN 2

// Secondary TPC mode
#define S_TPC_MODE_FIX 0
#define S_TPC_MODE_PARTIAL_TPC 1
#define S_TPC_MODE_PROTECT_P_SINR 2
#define S_TPC_MODE_PROTECT_P_SINR_AGGREGATE 3
// TPC mode
#define TPC_MODE_FIX 0
#define TPC_MODE_PARTIAL_TPC 1
// 
#define TPC_MODE_PROTECT_SINR 2
#define TPC_MODE_PROTECT_SINR_AGGREGATE 3
#define TPC_MODE_PROTECT_SINR_EQUAL_TX_POWER 4 // Not implemented yet
#define TPC_MODE_PROTECT_SINR_EQUAL_TX_POWER_AGGREGATE 5 // Not implemented yet
#define TPC_MODE_PROTECT_SINR_EQUAL_INTERFERENCE_POWER 6 // Not implemented yet
#define TPC_MODE_PROTECT_SINR_EQUAL_RX_INTERFERENCE_AGGREGATE 7 // Not implemented yet
// Cooperative power control related
#define TPC_MODE_COOPERATIVE_POWER_CONTROL 10 // 
#define TPC_MODE_COOPERATIVE_POWER_CONTROL_AGGREGATE 11
#define TPC_MODE_COOPERATIVE_POWER_AND_PROTECT_SINR 12
#define TPC_MODE_COOPERATIVE_POWER_AND_PROTECT_SINR_AGGREGATE 13

// 2012.02.01
#define TPC_PROTECTION_TARGET_EXIST 1
#define TPC_PROTECTION_TARGET_NONE 0

// Secondary nodes' position distribution
#define S_NODE_ANGLE_UNIFORM 1
#define S_NODE_ANGLE_RANDOM 0

// Secondary nodes' distance distribution
#define S_NODE_DISTANCE_FIX 0
#define S_NODE_DISTANCE_RANDOM 1

// Connection ability
#define CONNECT_ABILITY_PRIMARY_ONLY 0
#define CONNECT_ABILITY_SECONDARY_ONLY 1
#define CONNECT_ABILITY_BOTH 2

// Serving system index
#define SERVING_SYSTEM_NONE -1 // out of service areas of any systems. 2012.01.25: Not used in the simulation yet. 
#define SERVING_SYSTEM_PRIMARY 0
#define SERVING_SYSTEM_SECONDARY 1

// 2012.02.02
#define LOWER_LIMIT 0
#define UPPER_LIMIT 1

// 2012.05.21
#define WEIGHT_MATRIX_TYPE_WITHOUT_COMBINING -1 
#define WEIGHT_MATRIX_TYPE_MRC 0 // Only for NumTxAntenna = 1. 
#define WEIGHT_MATRIX_TYPE_MMSE 1
#define WEIGHT_MATRIX_TYPE_ZF 2 
#define WEIGHT_MATRIX_TYPE_MMSE_IRC 3 
#define WEIGHT_MATRIX_TYPE_MMSE_MRC 4 // Only for NumTxAntenna = 1. 
#define WEIGHT_MATRIX_TYPE_ZF_MRC 5 // Only for NumTxAntenna = 1. 
#define WEIGHT_MATRIX_TYPE_MMSE_IRC_MRC 6 // Only for NumTxAntenna = 1. 

// 2012.05.27
#define RB_UTILIZATION_MODE_FULL_BANDWIDTH 0
#define RB_UTILIZATION_MODE_EQUAL_DIVISION_PER_SECTOR 1

// 2012.09.25 
#define TYPE_ALMOST_BLANK_SUBFRAME_NORMAL_FRAME -1
#define TYPE_ALMOST_BLANK_SUBFRAME_ZERO_POWER 1
#define TYPE_ALMOST_BLANK_SUBFRAME_REDUCED_POWER 2

#define FLAG_SERVING_SITE 0 
#define FLAG_NEIGHBOR_SITE 1
#define FLAG_NOISE 2
#define FLAG_GEOMETRY_SERVING_SITE 10
#define FLAG_GEOMETRY_NEIGHBOUR_SITE 11
#define FLAG_GEOMETRY_NOISE 12

// 2012.09.27 added
#define FLAG_PATH_LOSS_SCM_CALC 0
#define FLAG_PATH_LOSS_SCM_SKIP 1

// 2013.06.10 
#define SCHEDULE_CHANGE_MODE_BASED_ON_POWER_HEADROOM_NOT_CONSIDERED -1
#define SCHEDULE_CHANGE_MODE_BASED_ON_POWER_HEADROOM_REDUCE 0
#define SCHEDULE_CHANGE_MODE_BASED_ON_POWER_HEADROOM_STOP 1

// 2013.06.17
#define MODULATION_ORDER_ZERO 0
#define MODULATION_ORDER_QPSK 2 
#define MODULATION_ORDER_16QAM 4 
#define MODULATION_ORDER_64QAM 6 

// 2013.07.05 
#define MAX_NUM_CODEWORD 1
#define MAX_NUM_PMI_STAGE 1
#define MAX_NUM_SPATIAL_LAYER_DL 1
#define MAX_NUM_SPATIAL_LAYER_UL 1
#define MAX_NUM_SPATIAL_LAYER ( (MAX_NUM_SPATIAL_LAYER_DL > MAX_NUM_SPATIAL_LAYER_UL) ? MAX_NUM_SPATIAL_LAYER_DL : MAX_NUM_SPATIAL_LAYER_UL )

// 2013.04.19
#define MAX_NUM_CELL_ID 504 
#define MAX_NUM_USER_ID 65536 // 2-16

// 2013.05.15
#define MAX_DELAY_DUE_TO_BACKHAUL_IN_SUBFRAME 500 // Max backhaul delay which can be considered in the simulation

// 2013.07.24 
#define CELL_LAYOUT_MODE_HEXAGONAL 0
#define CELL_LAYOUT_MODE_INDOOR 1 

// 2013.09.02 
#define FIXED_NLOS_MODE_ITUR_M2135_NONE -1
#define FIXED_NLOS_MODE_ITUR_M2135_NLOS 0
#define FIXED_NLOS_MODE_ITUR_M2135_LOS 1

// 
#define HARQ_SET_FLAG_RETRANSMISSION_HANDOVER 0
#define HARQ_SET_FLAG_RETRANSMISSION_BLOCK_ERROR 1

//
#define MIN_IDX_TBS_FOR_QPSK 0
#define MAX_IDX_TBS_FOR_QPSK 9
#define MIN_IDX_TBS_FOR_16QAM 9
#define MAX_IDX_TBS_FOR_16QAM 15
#define MIN_IDX_TBS_FOR_64QAM 15
#define MAX_IDX_TBS_FOR_64QAM 26

//
#define MAX_NUM_SUPERPOSITION_LAYER 1


// 
#define NODE_POSITION_MODE_PRIAMRY_BS 0 
#define NODE_POSITION_MODE_UNIFORM_DISTRIBUTION_OVER_PRIMARY_SECTOR 1
#define NODE_POSITION_MODE_UNIFORM_DISTRIBUTION_OVER_SECONDARY_SECTOR 2
#define NODE_POSITION_MODE_CIRCLE_DISTRIBUTION_OVER_PRIMARY_SECTOR 3


// 2014.01.11 
#define ANTENNA_MODE_TX 0 
#define ANTENNA_MODE_RX 1

// 2014.02.21 
#define INITIAL_POSITION_MODE_REGULAR 0 
#define INITIAL_POSITION_MODE_POINT_PROCESS 1 

#define NUM_PRIMARY_BS_HEXAGONAL_1 1
#define NUM_PRIMARY_BS_HEXAGONAL_7 7
#define NUM_PRIMARY_BS_HEXAGONAL_19 19





// For sector
const double pdAngleSectorBoreSight03Rad[3] = {
    1.0 / 6.0 * PI, 
    5.0 / 6.0 * PI, 
    9.0 / 6.0 * PI
};
const double pdAngleSectorBoreSight06Rad[6] = {
    1.0 / 6.0 * PI, 
    3.0 / 6.0 * PI, 
    5.0 / 6.0 * PI, 
    7.0 / 6.0 * PI, 
    9.0 / 6.0 * PI, 
    11.0 / 6.0 * PI
};

// CarrierAggregationCapability
#define MAX_NUM_CARRIER_AGGREGATION_BAND 1
#define MAX_NUM_RESOURCE_BLOCK_PER_BS 100  // 
#define CHANNEL_ESTIMATION_ERROR_FLAG_OFF 1
#define CHANNEL_ESTIMATION_ERROR_FLAG_ON 0


#endif 

// End of file
