/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mface_thu_edu_cn_mface_PointFaceLib */

#ifndef _Included_mface_thu_edu_cn_mface_PointFaceLib
#define _Included_mface_thu_edu_cn_mface_PointFaceLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mface_thu_edu_cn_mface_PointFaceLib
 * Method:    nativePoint
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_mface_thu_edu_cn_mface_PointFaceLib_nativePoint
  (JNIEnv * env, jobject obj, jlong address, jint flag,  jstring js1, jstring js2, jstring js3);


#ifdef __cplusplus
}
#endif
#endif
